// This file will be auto-generated by: npm run supabase:gen-types
// For now, we'll define basic types manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type UserRole = 'admin' | 'user'
export type PencaStatus = 'draft' | 'open' | 'in_progress' | 'closed'
export type RaceStatus = 'scheduled' | 'closed' | 'result_published'
export type MembershipRole = 'player'

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          display_name: string
          avatar_url: string | null
          role: UserRole
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          display_name: string
          avatar_url?: string | null
          role?: UserRole
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          display_name?: string
          avatar_url?: string | null
          role?: UserRole
          created_at?: string
          updated_at?: string
        }
      }
      pencas: {
        Row: {
          id: string
          slug: string
          name: string
          description: string | null
          status: PencaStatus
          rules_version_active: number | null
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          name: string
          description?: string | null
          status?: PencaStatus
          rules_version_active?: number | null
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          name?: string
          description?: string | null
          status?: PencaStatus
          rules_version_active?: number | null
          created_by?: string
          created_at?: string
          updated_at?: string
        }
      }
      rulesets: {
        Row: {
          id: string
          penca_id: string
          version: number
          points_top3: Json
          modalities_enabled: Json
          tiebreakers_order: Json
          lock_minutes_before_start: number
          sealed_predictions_until_close: boolean
          effective_from_race_seq: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          penca_id: string
          version: number
          points_top3?: Json
          modalities_enabled?: Json
          tiebreakers_order?: Json
          lock_minutes_before_start?: number
          sealed_predictions_until_close?: boolean
          effective_from_race_seq?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          penca_id?: string
          version?: number
          points_top3?: Json
          modalities_enabled?: Json
          tiebreakers_order?: Json
          lock_minutes_before_start?: number
          sealed_predictions_until_close?: boolean
          effective_from_race_seq?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      races: {
        Row: {
          id: string
          penca_id: string
          seq: number
          venue: string
          distance_m: number
          track_condition: string | null
          start_at: string
          status: RaceStatus
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          penca_id: string
          seq: number
          venue: string
          distance_m: number
          track_condition?: string | null
          start_at: string
          status?: RaceStatus
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          penca_id?: string
          seq?: number
          venue?: string
          distance_m?: number
          track_condition?: string | null
          start_at?: string
          status?: RaceStatus
          created_at?: string
          updated_at?: string
        }
      }
      race_entries: {
        Row: {
          id: string
          race_id: string
          program_number: number
          horse_name: string
          jockey: string | null
          trainer: string | null
          stud: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          race_id: string
          program_number: number
          horse_name: string
          jockey?: string | null
          trainer?: string | null
          stud?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          race_id?: string
          program_number?: number
          horse_name?: string
          jockey?: string | null
          trainer?: string | null
          stud?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      predictions: {
        Row: {
          id: string
          race_id: string
          user_id: string
          winner_pick: string | null
          exacta_pick: Json | null
          trifecta_pick: Json | null
          tiebreaker_value: string | null
          submitted_at: string
          is_locked: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          race_id: string
          user_id: string
          winner_pick?: string | null
          exacta_pick?: Json | null
          trifecta_pick?: Json | null
          tiebreaker_value?: string | null
          submitted_at?: string
          is_locked?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          race_id?: string
          user_id?: string
          winner_pick?: string | null
          exacta_pick?: Json | null
          trifecta_pick?: Json | null
          tiebreaker_value?: string | null
          submitted_at?: string
          is_locked?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      race_results: {
        Row: {
          race_id: string
          official_order: Json
          first_place_tie: boolean
          notes: string | null
          published_at: string
          published_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          race_id: string
          official_order: Json
          first_place_tie?: boolean
          notes?: string | null
          published_at?: string
          published_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          race_id?: string
          official_order?: Json
          first_place_tie?: boolean
          notes?: string | null
          published_at?: string
          published_by?: string
          created_at?: string
          updated_at?: string
        }
      }
      scores: {
        Row: {
          id: string
          penca_id: string
          race_id: string
          user_id: string
          points_total: number
          breakdown: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          penca_id: string
          race_id: string
          user_id: string
          points_total?: number
          breakdown?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          penca_id?: string
          race_id?: string
          user_id?: string
          points_total?: number
          breakdown?: Json
          created_at?: string
          updated_at?: string
        }
      }
      memberships: {
        Row: {
          penca_id: string
          user_id: string
          role: MembershipRole
          joined_at: string
        }
        Insert: {
          penca_id: string
          user_id: string
          role?: MembershipRole
          joined_at?: string
        }
        Update: {
          penca_id?: string
          user_id?: string
          role?: MembershipRole
          joined_at?: string
        }
      }
      invites: {
        Row: {
          id: string
          penca_id: string
          code: string
          expires_at: string | null
          max_uses: number | null
          uses: number
          created_by: string
          created_at: string
        }
        Insert: {
          id?: string
          penca_id: string
          code: string
          expires_at?: string | null
          max_uses?: number | null
          uses?: number
          created_by: string
          created_at?: string
        }
        Update: {
          id?: string
          penca_id?: string
          code?: string
          expires_at?: string | null
          max_uses?: number | null
          uses?: number
          created_by?: string
          created_at?: string
        }
      }
      penca_admins: {
        Row: {
          penca_id: string
          user_id: string
          created_at: string
        }
        Insert: {
          penca_id: string
          user_id: string
          created_at?: string
        }
        Update: {
          penca_id?: string
          user_id?: string
          created_at?: string
        }
      }
      audit_log: {
        Row: {
          id: string
          actor_id: string
          action: string
          target_table: string
          target_id: string | null
          diff: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          actor_id: string
          action: string
          target_table: string
          target_id?: string | null
          diff?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          actor_id?: string
          action?: string
          target_table?: string
          target_id?: string | null
          diff?: Json | null
          created_at?: string
        }
      }
    }
    Views: {
      penca_leaderboard: {
        Row: {
          penca_id: string
          user_id: string
          display_name: string
          avatar_url: string | null
          total_points: number
          races_participated: number
          race_details: Json
        }
      }
      upcoming_races: {
        Row: {
          id: string
          penca_id: string
          penca_name: string
          seq: number
          venue: string
          distance_m: number
          track_condition: string | null
          start_at: string
          status: RaceStatus
          lock_minutes_before_start: number
          lock_at: string
          entries_count: number
          predictions_count: number
        }
      }
    }
    Functions: {
      is_penca_admin: {
        Args: {
          penca_id_param: string
          user_id_param: string
        }
        Returns: boolean
      }
      is_penca_member: {
        Args: {
          penca_id_param: string
          user_id_param: string
        }
        Returns: boolean
      }
      is_prediction_locked: {
        Args: {
          race_id_param: string
        }
        Returns: boolean
      }
    }
  }
}
